
POST http://localhost:9000/api/register
Content-Type: application/json

{
  "id": "",
  "email": "eu.tuhin@gmail.com",
  "username": "hridoy",
  "password": "hridoy123",
  "role": ["user"],
  "enabled": true
}
> {% client.global.set("access_token", response.body.access_token);  %}


###
POST http://localhost:9000/api/login
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "username": "hridoy",
  "password": "hridoy123"
}
