
POST http://localhost:9000/employee-basic-info
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "id": "",
  "name": "Abdullah Hridoy",
  "address": "Jashore, Jashore-1212",
  "paymentTypeEnumKey": "PENDING",
  "paymentTypeEnumValue": "Pending",
  "designationTypeEnumKey": "EXECUTIVE",
  "designationTypeEnumValue": "Executive",
  "employeeAccountDto": null,
  "employeeAccountTransactionDto": null,
  "employeeAttendanceDto": null,
  "employeeBankInfoDto": null,
  "enabled": true
}
